version: 0.2

phases:
  build:
    commands:
      - mv wp-config-sample.php wp-config.php
      - sed -i 's/database_name_here/shibracicd/g' wp-config.php
      - sed -i 's/username_here/pipeline/g' wp-config.php
      - sed -i 's/password_here/pipeline/g' wp-config.php
      - sed -i 's/localhost/shibracicd.cfdyrms3ajre.ap-south-1.rds.amazonaws.com/g' wp-config.php
artifacts:
  files:
    - "**/*"
